config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#welcome'
  get 'oauth_connect' => 'users#oauth_connect', as: 'instagram_oauth'
  get 'oauth_callback' => 'users#oauth_callback'
  get 'logout' => 'users#logout', as: 'logout'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def oauth_connect
    redirect_to Instagram.authorize_url(:redirect_uri => "https://floating-wave-4718.herokuapp.com/oauth_callback")
  end

  def oauth_callback
    response = Instagram.get_access_token(params[:code], :redirect_uri => "https://floating-wave-4718.herokuapp.com/oauth_callback")
    @user = User.find_by(instagram_token: response.access_token)
    @user = User.create(instagram_token: response.access_token) unless @user
    session[:user_id] = @user.id
    render :index
  end

  def logout
    session.clear
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def welcome
    render :welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramHeroku</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if logged_in? %>
      <%= link_to "Logout", logout_path %>
    <% else %>
      <%= link_to "Sign in with Instagram", instagram_oauth_path %>
    <% end %>
  </header>
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<%= @user.inspect %>

app/views/welcome/welcome.html.erb
Welcome to the Jungle.